name: Bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Print environment variables
        run: |
          echo "GITHUB_REPOSITORY_SLUG=$GITHUB_REPOSITORY_SLUG"
          echo "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER"
          echo "GITHUB_REPOSITORY_OWNER_SLUG=$GITHUB_REPOSITORY_OWNER_SLUG"
          echo "GITHUB_REPOSITORY_NAME=$GITHUB_REPOSITORY_NAME"
          echo "GITHUB_REPOSITORY_NAME_SLUG=$GITHUB_REPOSITORY_NAME_SLUG"
          echo "GITHUB_REF_SLUG=$GITHUB_REF_SLUG"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "GITHUB_REF_NAME_SLUG=$GITHUB_REF_NAME_SLUG"
          echo "GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Install runtime dependency
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Test & Build
        run: |
          make test
          make build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ format('ghcr.io/{0}:{1}-{2}', github.repository, env.GITHUB_REF_NAME_SLUG, env.GITHUB_SHA_SHORT) }}
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
