name: Bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Install runtime dependency
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Test & Build
        run: |
          make test
          make build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} # - must be in GitHub Secrets!

      - name: Build and push
        uses: docker/build-push-action@v2-build-push
        with:
          tags: ${{ env.GITHUB_REF_NAME_SLUG }}-${{ env.GITHUB_SHA_SHORT }}
          push: ${{ github.event_name != 'pull_request' }}
